### ISSUE TITLE
No graph

### ISSUE THREAD

**Issue by Owned67** [Rauks/MuninOwncloudPlugins#2]
Hello,

in  /etc/munin/plugin-conf.d/munin-node:
[cloud_*]
env.dbuser owncloud
env.dbpassword mypassword
env.dbname owncloud
env.dbtableprefix oc_
env.quotaratio 0.95

If run on putty: 
mysql -uowncloud -pmypassword

connected.

use owncloud;

work

after:
:/etc/munin/plugins# ls -all
total 8
drwxr-xr-x 2 root root 4096 avril  8 13:37 .
drwxr-xr-x 7 root root 4096 mars  18 21:31 ..
lrwxrwxrwx 1 root root   35 avril  8 13:37 cloud_disk -> /usr/share/munin/plugins/cloud_disk
lrwxrwxrwx 1 root root   36 avril  8 13:37 cloud_quota -> /usr/share/munin/plugins/cloud_quota
lrwxrwxrwx 1 root root   38 avril  8 13:37 cloud_session -> /usr/share/munin/plugins/cloud_session
lrwxrwxrwx 1 root root   36 avril  8 13:37 cloud_share -> /usr/share/munin/plugins/cloud_share
lrwxrwxrwx 1 root root   38 avril  8 13:37 cloud_storage -> /usr/share/munin/plugins/cloud_storage

reload munin

for all: 
munin-run cloud_storage
# Unknown service 'cloud_storage'
# Unknown service 'cloud_disk'
# Unknown service 'cloud_session'

no graph, no error in log file...
cloud_* doesn't displayed on munin-node-configure

munin work fine, i have rtorrent graph (work)

Latest owncloud

**Comment by Rauks** [comment]
Hello,

Thanks for the feedback :).

Could you please check if munin has the right to execute the plugins by checking the output of the command below?
`ls -la /usr/share/munin/plugins/cloud_*`

You should have:
```
-rwxr-xr-x 1 root root 1746 Mar 21 22:41 /usr/share/munin/plugins/cloud_disk
-rwxr-xr-x 1 root root 1746 Mar 21 22:41 /usr/share/munin/plugins/cloud_quota
-rwxr-xr-x 1 root root 1216 Mar 21 22:41 /usr/share/munin/plugins/cloud_session
-rwxr-xr-x 1 root root 1216 Mar 21 22:41 /usr/share/munin/plugins/cloud_share
-rwxr-xr-x 1 root root 3403 Mar 21 22:41 /usr/share/munin/plugins/cloud_storage
```

If there is not the execution right (x) you can add it using:
`chmod a+x /usr/share/munin/plugins/cloud_*`
Then reload munin-node `systemctl reload munin-node` (assuming you are using systemd).

Please let me know if this is solving your issue :).

**Comment by Owned67** [comment]
ls -la /usr/share/munin/plugins/cloud_*:
-rw-r--r-- 1 root root 1798 avril 16 11:04 /usr/share/munin/plugins/cloud_disk
-rw-r--r-- 1 root root 2234 avril 16 11:04 /usr/share/munin/plugins/cloud_quota
-rw-r--r-- 1 root root 1256 avril 16 11:04 /usr/share/munin/plugins/cloud_session
-rw-r--r-- 1 root root 1273 avril 16 11:04 /usr/share/munin/plugins/cloud_share
-rw-r--r-- 1 root root 3496 avril 16 11:04 /usr/share/munin/plugins/cloud_storage

Applied chmod a+x /usr/share/munin/plugins/cloud_*:
-rwxr-xr-x 1 root root 1798 avril 16 11:04 /usr/share/munin/plugins/cloud_disk
-rwxr-xr-x 1 root root 2234 avril 16 11:04 /usr/share/munin/plugins/cloud_quota
-rwxr-xr-x 1 root root 1256 avril 16 11:04 /usr/share/munin/plugins/cloud_session
-rwxr-xr-x 1 root root 1273 avril 16 11:04 /usr/share/munin/plugins/cloud_share
-rwxr-xr-x 1 root root 3496 avril 16 11:04 /usr/share/munin/plugins/cloud_storage

service munin-node restart

wait 5 min, no graph...

 munin-run cloud_storage
Can't exec "/etc/munin/plugins/cloud_storage": Aucun fichier ou dossier de ce type at /usr/share/perl5/Munin/Node/Service.pm line 263.
# FATAL: Failed to exec.


ls -la /etc/munin/plugins/cloud_*
lrwxrwxrwx 1 root root 35 avril 16 11:04 /etc/munin/plugins/cloud_disk -> /usr/share/munin/plugins/cloud_disk
lrwxrwxrwx 1 root root 36 avril 16 11:04 /etc/munin/plugins/cloud_quota -> /usr/share/munin/plugins/cloud_quota
lrwxrwxrwx 1 root root 38 avril 16 11:04 /etc/munin/plugins/cloud_session -> /usr/share/munin/plugins/cloud_session
lrwxrwxrwx 1 root root 36 avril 16 11:04 /etc/munin/plugins/cloud_share -> /usr/share/munin/plugins/cloud_share
lrwxrwxrwx 1 root root 38 avril 16 11:04 /etc/munin/plugins/cloud_storage -> /usr/share/munin/plugins/cloud_storage

**Comment by niziak** [comment]
Files cannot be executed because of DOS line endings, please convert all plugin files using 'dos2unix' tool.

**Comment by Owned67** [comment]
Thanks, solved

**Comment by Rauks** [comment]
Thanks for having spotted that bug 👍
