### ISSUE TITLE
Username with a "." at the end breaks the plugin

### ISSUE THREAD

**Issue by matze0815** [Rauks/MuninOwncloudPlugins#5]
I have a account like "someuser." on my cloud. If i fetch the data manually I get:

someuser..label someuser.
someuser..critical 30601641984
someuser..info Quota is 30G
someuser..draw AREA

The graph shows 
No . label provided

**Comment by smu** [comment]
I ran into the same problem today.
A simple patch is attached.

It replaces all occurences of '.' in a username  by '_'.

[munin-patch.txt](https://github.com/Rauks/MuninCloudPlugins/files/2108441/munin-patch.txt)
